yangsunghun/FitFor

.vscode/settings.json, next.config.mjs, package.json, src/app/home/mock_data.ts, src/app/home/page.tsx, src/app/layout.tsx, src/components/providers/TQProvider.tsx, src/lib/types/supabase.ts, yarn.lock
- 리스트 형식 토글 기능 추가
- next.config.mjs (임시 데이터 외부 이미지 사용)
- src/app/home/page.tsx (컴포넌트 분리 없이 메인페이지에 모두 작성)
- 2025.01.07
- 고심 끝에 react-layout-masonry 라이브러리로 결정했습니다.
=> feat: 리스트 형식 토글 기능 추가

src/app/detail/[id]/page.tsx, src/app/detail/page.tsx, src/app/home/_components/ListLayout.tsx, src/app/home/_components/ListLender.tsx, src/app/home/_components/MasonryLayout.tsx, src/app/home/page.tsx, src/lib/styles/globals.css, src/lib/utils/post/fetchPost.ts, src/lib/utils/post/fetchPostDetail.ts, tailwind.config.ts
- 메인페이지 필터링 기능 추가
- src/app/home/_components/ListLayout.tsx
- src/app/home/_components/MasonryLayout.tsx
- src/lib/utils/post/fetchPostDetail.ts
- tailwind.config.ts
- 2024.01.08
- 메인페이지 필터링 기능 추가
- 기본 css 삭제했습니다.
- 상세페이지 기본적인 기능 추가했습니다
=> feat: 메인페이지 필터링 기능 추가

next.config.mjs
- 카카오 유저 프로필 안 뜨는 이슈 해결
- next.config.mjs
- 2025.01.09
- 버그픽스
=> fix: 카카오 유저 프로필 안 뜨는 이슈 해결

tailwind.config.ts
-feat: 폰트 사이즈 지정 완료
- tailwind.config.ts
- 2025.01.10
- 폰트 사이즈 맞게 사용하시면 됩니다, font-weight는 tailwind의 font-bold, font-medium, font-regular 사용하시면 됩니다.
=> feat: 폰트 사이즈 지정 완료

src/app/@modal/(.)detail/[id]/view/page.tsx, src/app/detail/[id]/page.tsx, src/app/detail/_components/ButtonWrap.tsx, src/app/detail/_components/ToggleButton.tsx, src/app/home/_components/ListLayout.tsx, src/app/home/_components/ListLender.tsx, src/app/search/page.tsx, src/lib/hooks/detail/useBookmark.ts, src/lib/hooks/detail/useLike.ts, src/lib/types/supabase.ts, src/lib/utils/detail/toggleState.ts, src/lib/utils/post/fetchPost.ts, src/lib/utils/post/fetchPostDetail.ts
- 좋아요, 북마크 기능 추가
- src/app/@modal/(.)detail/[id]/view/page.tsx
- src/app/detail/_components/ButtonWrap.tsx
- src/app/detail/_components/ToggleButton.tsx
- src/app/home/_components/ListLayout.tsx
- src/app/home/_components/ListLender.tsx
- src/app/search/page.tsx
- src/lib/hooks/detail/useBookmark.ts
- src/lib/utils/detail/toggleState.ts
- 2024.01.10
- post 페칭하는 함수 utils 로 이동했습니다
=> feat: 좋아요, 북마크 기능 추가

src/app/detail/[id]/page.tsx, src/app/detail/_components/CommentSection.tsx, src/app/detail/_components/LikeSection.tsx, src/lib/hooks/detail/useComment.ts, src/lib/types/supabase.ts, src/lib/utils/detail/comments.ts
- 게시물 댓글 기능 프로토타입 추가
- src/app/detail/_components/CommentSection.tsx
- src/lib/hooks/detail/useComment.ts
- src/lib/utils/detail/comments.ts
- 2025.01.11
- 댓글 요청 관련 api, 커스텀훅 추가
- CommentSection 내부 컴포넌트 분리 예정
=> feat: 게시물 댓글 기능 추가

src/app/home/_components/LayoutToggle.tsx, src/app/home/_components/ListLender.tsx, src/app/home/_components/TagsFilter.tsx, src/app/search/_components/Pagination.tsx, src/app/search/_components/SearchForm.tsx, src/app/search/_components/SearchResults.tsx, src/app/search/page.tsx, src/components/layout/HeaderContent.tsx, src/lib/hooks/home/usePosts.ts, src/lib/hooks/search/useSearchPosts.ts, src/lib/hooks/search/useSearchQuery.ts, src/lib/utils/search/fetchSearchPosts.tsx
- 검색 기능 추가
- src/app/home/_components/LayoutToggle.tsx
- src/app/home/_components/TagsFilter.tsx
- src/app/search/_components/Pagination.tsx
- src/app/search/_components/SearchForm.tsx
- src/app/search/_components/SearchResults.tsx
- src/app/search/page.tsx
- src/lib/hooks/home/usePosts.ts
- src/lib/hooks/search/useSearchPosts.ts
- src/lib/hooks/search/useSearchQuery.ts
- src/lib/utils/search/fetchSearchPosts.tsx
- 2025.01.12
- 헤더 input으로 검색 기능 옮겼습니다.
=> feat: 검색 기능 추가

src/app/detail/_components/CommentSection.tsx, src/app/detail/_components/LikeSection.tsx, src/app/detail/_components/ToggleButton.tsx, src/app/page.tsx, src/lib/hooks/search/useSearchQuery.ts
- UX 관련 간단하게 보완
- src/app/detail/_components/CommentSection.tsx
- src/app/detail/_components/LikeSection.tsx
- src/app/detail/_components/ToggleButton.tsx
- src/app/page.tsx
- src/lib/hooks/search/useSearchQuery.ts
- 2025.01.13
- 모든 페이지에서 검색 가능
- 비회원 좋아요 북마크 댓글 시 alert 추가
- /home 으로 기본페이지 리다이렉트
=> refactor: UX 관련 간단하게 보완

src/app/chat/[id]/_components/ChatInput.tsx, src/app/chat/[id]/_components/ChatMessages.tsx, src/app/chat/[id]/page.tsx, src/app/chat/new/_components/ThumbnailImage.tsx, src/app/chat/new/_components/ThumbnailModal.tsx
- feat: 채팅방 생성 시 이미지 업로드 모달, 채팅방 메시지 정렬 UI 변경
- src/app/chat/[id]/_components/ChatInput.tsx
- src/app/chat/[id]/_components/ChatMessages.tsx
- src/app/chat/[id]/page.tsx
- src/app/chat/new/_components/ThumbnailImage.tsx
- src/app/chat/new/_components/ThumbnailModal.tsx
- 2025.01.13
- 채팅방 생성 시 이미지 업로드용 모달이 추가되었습니다.(이미지 미리보기 포함) 
- 채팅방 메시지 정렬 UI가 변경되었습니다.
- 채팅에서 이미지 첨부 기능이 추가되었습니다.
=> feat: 채팅방 생성 시 이미지 업로드 모달, 채팅방 메시지 정렬 UI 변경

src/app/home/_components/ListLender.tsx, src/app/home/_components/MasonryLayout.tsx, src/app/home/page.tsx, src/app/layout.tsx, src/components/layout/Header.tsx, src/components/layout/HeaderContent.tsx, src/components/ui/Button.tsx, src/lib/styles/globals.css, tailwind.config.ts
- header 시안대로 수정
- src/app/layout.tsx
- src/components/layout/Header.tsx
- src/components/ui/Button.tsx
- src/lib/styles/globals.css
- 2024.01.14
- 디자인 기반하여 inner 라는 유틸리티 class 생성 했습니다. 콘텐츠 영역 폭입니다.
- 버튼 컴포넌트 line-height 수정했습니다
- tailwind 자간 실수로 소수점에 0 더붙였어서 수정했습니다
=> style: header 시안대로 수정

src/app/detail/_components/LikeSection.tsx, src/app/detail/_components/ToggleButton.tsx, src/app/home/_components/LayoutToggle.tsx, src/app/home/_components/ListLayout.tsx, src/app/home/_components/ListLender.tsx, src/app/home/_components/MasonryLayout.tsx, src/app/layout.tsx, src/components/ui/Tags.tsx, src/lib/utils/post/fetchPost.ts, tailwind.config.ts
- 메인페이지 스타일링
- src/app/detail/_components/LikeSection.tsx
- src/app/detail/_components/ToggleButton.tsx
- src/app/home/_components/LayoutToggle.tsx
- src/app/home/_components/ListLayout.tsx
- src/app/home/_components/ListLender.tsx
- src/app/home/_components/MasonryLayout.tsx
- src/app/layout.tsx
- src/components/ui/Tags.tsx
- src/lib/utils/post/fetchPost.ts
- 2025.01.14
- 태그 컴포넌트 제작했습니다.
=> style: 메인페이지 스타일링

src/app/detail/[id]/page.tsx, src/app/detail/_components/ContentsSection.tsx, src/app/detail/_components/LikeSection.tsx, src/app/detail/_components/ToggleButton.tsx, src/app/home/_components/ListLayout.tsx, src/app/home/_components/MasonryLayout.tsx, src/lib/utils/common/formatDateTime.ts
- 식사 맛있게 하세요
- src/app/detail/_components/ContentsSection.tsx
- src/app/detail/_components/LikeSection.tsx
- src/app/detail/_components/ToggleButton.tsx
- src/app/home/_components/ListLayout.tsx
- src/app/home/_components/MasonryLayout.tsx
- src/lib/utils/common/formatDateTime.ts
- 2025.01.14
- 좋아요 북마크는 모든 곳에서 사용할 수 있게 되었습니다
=> feat: 날짜, 시간 포맷 관련 유틸함수 추가

src/app/@modal/(.)detail/[id]/view/page.tsx, src/app/detail/[id]/page.tsx, src/app/detail/_components/CommentSection.tsx, src/app/detail/_components/ContentsSection.tsx, src/app/detail/_components/LikeSection.tsx, src/app/detail/_components/ToggleButton.tsx, src/app/home/_components/ListLayout.tsx, src/lib/styles/globals.css
- 상세페이지 스타일링
- 상세페이지 수정했습니다.
- 2024.01.14
- 1줄 말줄임, 2줄 말줄임 apply css 추가했습니다.
=> style: 상세페이지 스타일링

src/app/detail/[id]/page.tsx, src/app/detail/_components/CommentSection.tsx, src/app/detail/_components/ContentsSection.tsx, src/app/detail/_components/LikeSection.tsx, src/app/detail/_components/PurchaseList.tsx, src/app/home/_components/ListLayout.tsx, src/app/search/page.tsx, src/components/shared/ListItem.tsx, src/lib/hooks/detail/usePostDetail.ts, src/lib/hooks/detail/usePurchases.ts, src/lib/styles/globals.css, src/lib/types/post.ts, src/lib/utils/detail/fetchPurchases.ts
- 게시글 구매처 출력하기
- src/app/detail/_components/PurchaseList.tsx
- src/lib/hooks/detail/usePurchases.ts
- src/lib/utils/detail/fetchPurchases.ts
- 2024.01.15
- 나머지는 자잘한(컨벤션 등) 수정
- 썸네일 전용 유틸리티 클래스 .thumbnail 만들었습니다.
이렇게 쓰시면 되고 Image 에는 fill={true} attribute가 있어야 합니다
=> feat: 구매처 출력하기

src/app/detail/_components/ViewCounter.tsx, src/app/mypage/_components/MypageMenu.tsx, src/app/mypage/_components/RecentViewPosts.tsx, src/lib/hooks/mypage/useRecentViewPosts.ts, src/lib/utils/detail/addRecentView.ts, src/lib/utils/mypage/userInfo.ts, src/lib/utils/mypage/userRecentViews.ts
- feat: 최근 본 게시물 탭 구현
- app/detail/_components/ViewCounter.tsx
- app/mypage/_components/MyPageMenu.tsx
- app/mypage/_components/RecentViewPosts.tsx
- lib/hooks/mypage/useRecentViewPosts.ts
- lib/utils/detail/addRecentView.ts
- lib/utils/mypage/userInfo.ts
- lib/utils/mypage/userRecentViews.ts
- 2025.01.15
=> feat: 최근 본 게시물 탭 구현

package.json, src/app/detail/_components/CommentSection.tsx, src/app/detail/_components/ContentsSection.tsx, src/app/detail/_components/ImageGallery.tsx, src/app/home/_components/ListLender.tsx, src/components/common/Carousel.tsx, src/components/shared/LikeSection.tsx, src/components/shared/ListPost.tsx, src/components/shared/ToggleButton.tsx, src/components/ui/FloatingButton.tsx, src/lib/hooks/detail/useBookmark.ts, src/lib/hooks/detail/useLike.ts, src/lib/styles/globals.css, src/lib/utils/common/formatDateTime.ts, src/lib/utils/detail/bookmarkActions.ts, src/lib/utils/detail/likeActions.ts, yarn.lock
- 좋아요 북마크 리팩토링
- 주된 수정은 좋아요 북마크 리팩토링인데 잡다합니다
- 2025.01.16
- swiper 캐러셀 추가했습니다.
- date-fns 라이브러리로 ~분 전,  ~시간 전으로 시간 표시 할 수 있습니다.
- 좋아요 북마크 붙어있는 LikeSection 은 그냥 이대로 쓰려고요.. 컴포넌트 나눠서 분기처리 하는게 오히려 더 힘들것같아서요
- 플러팅 버튼 추가했습니다.
=> feat: 좋아요 북마크 리팩토링

src/app/@modal/(.)detail/[id]/view/ModalButton.tsx, src/app/@modal/(.)detail/[id]/view/page.tsx, src/app/detail/[id]/page.tsx, src/app/detail/_components/CommentSection.tsx, src/app/detail/_components/ContentsSection.tsx, src/app/detail/_components/ImageGallery.tsx, src/app/detail/_components/PurchaseList.tsx, src/components/shared/LikeSection.tsx, src/components/shared/ListPost.tsx, src/components/ui/Button.tsx, src/lib/types/supabase.ts
- 상세페이지 스타일링 1차 완료
- src/app/detail/_components/CommentSection.tsx
- src/app/detail/_components/ImageGallery.tsx
- src/app/detail/_components/PurchaseList.tsx
- src/components/shared/LikeSection.tsx
- src/components/shared/ListPost.tsx
- 2025.01.16
- 상세페이지 완료했어요
=> style: 상세페이지 스타일링 1차 완료

src/app/write/_components/PurchaseModal.tsx, src/app/write/page.tsx, src/lib/types/supabase.ts
- fix: 상품 모달 필수 입력값 수정 및 파싱에러 수정
- src/app/write/_components/PurchaseModal.tsx
- src/lib/types/supabase.ts
- 2025.1.16
- 모달 필수 입력값 수정 (제목, 이미지업로드 링크만 필수로)
- gen type 파싱 에러 수정
- 공사하다가 생긴 공백 삭제
=> fix: 상품 모달 필수 입력값 수정 및 파싱에러 수정

src/app/mypage/_components/RecentViewPosts.tsx, src/app/mypage/_components/VerificationSection.tsx, src/app/mypage/profile-setting/_components/ProfileSettingsForm.tsx, src/lib/types/supabase.ts
- fix: build시 warning 제거
- app/mypage/_components/RecentViewPosts.tsx
- app/mypage/_components/VerificationSection.tsx
- app/mypage/_components/ProfileSettingsForm.tsx
- lib/types/supabase.ts
- 2025.01.16
=> fix: build시 warning 제거

src/lib/utils/auth/auth.ts
- fix: 회원정보 수정 후 재로그인시 데이터가 지워지는 오류 수정
- lib/utils/auth/auth.ts
- 2025.01.16
회원정보를 수정 후에 로그아웃 했다가 다시 로그인했을때, 수정된 정보가 다시 원상복귀되는 문제를 발견하여 수정했습니다.
=> fix: 회원정보 수정 후 재로그인시 데이터가 지워지는 오류 수정

src/lib/constants/constants.ts
- chore: 디자인 시안 변경에 따른 태그 그룹 정의
- src/lib/constants/constants.ts
- 2025.1.17
- 디자인 시안에 따른 title 긴급 수정
=> chore: 디자인 시안 변경에 따른 태그 그룹 정의

src/app/layout.tsx, src/app/search/_components/SortPosts.tsx, src/components/layout/Header.tsx, src/components/layout/HeaderContent.tsx, src/components/layout/SearchBar.tsx, src/lib/hooks/search/useSearchBar.ts, src/lib/styles/globals.css, src/lib/utils/common/extractUnicode.ts
- 검색창 보완
- src/app/layout.tsx
- src/app/search/_components/SortPosts.tsx
- src/components/layout/Header.tsx
- src/components/layout/SearchBar.tsx
- src/lib/hooks/search/useSearchBar.ts
- src/lib/utils/common/extractUnicode.ts
- 2025.01.17
- 헤더 디자인 바뀌어있길래 수정했습니다
=> refactor: 검색창 보완

src/app/mypage/_components/ProfileSection.tsx, src/app/mypage/profile-setting/_components/ProfileSettingsForm.tsx, src/components/providers/AuthProvider.tsx
- fix: 회원정보 수정 후 데이터 업데이트 안되는 기능 수정
- ProfileSection.tsx
- ProfileSettingForm.tsx
- AuthProvider.tsx
- 2025.01.17
- 회원정보 수정 로직 오류 해결
=> fix: 회원정보 수정 후 데이터 업데이트 안되는 기능 수정

src/app/home/_components/ListLender.tsx, src/app/home/_components/MasonryLayout.tsx, src/app/search/_components/SearchResults.tsx, src/app/write/_components/AddressModal.tsx, src/app/write/page.tsx
- 모달컴포넌트 사용 예시
- 모달컴포넌트 사용 예시
- 2025.01.17
- 모달컴포넌트 사용 예시
=> 모달컴포넌트 사용 예시

src/app/mypage/_components/AccountSettingTabs.tsx, src/app/mypage/_components/MyPosts.tsx, src/app/mypage/_components/RecentViewPosts.tsx, src/app/mypage/_components/VerificationSection.tsx, src/app/mypage/profile-setting/_components/CameraButton.tsx, src/app/mypage/profile-setting/_components/GenderSelection.tsx, src/app/mypage/profile-setting/_components/ProfileEditTextField.tsx, src/app/mypage/profile-setting/_components/ProfileImageUploadSection.tsx, src/app/mypage/profile-setting/_components/ProfileSettingsForm.tsx, src/app/mypage/profile-setting/page.tsx, src/lib/validations/profileSettingSchema.ts
- refactor: 회원정보 수정 폼 리팩터링
- app/mypage/_components/AccountSettingTabs.tsx
- app/mypage/_components/MyPosts.tsx
- app/mypage/_components/RecentViewPosts.tsx
- app/mypage/_components/VerificationSection.tsx
- app/mypage/profile-setting/_components/CameraButton.tsx
- app/mypage/profile-setting/_components/GenderSelection.tsx
- app/mypage/profile-setting/_components/ProfileEditTextField.tsx
- app/mypage/profile-setting/_components/ProfileImageUploadSection.tsx
- app/mypage/profile-setting/_components/ProfileSettingsForm.tsx
- app/mypage/profile-setting/page.tsx
- lib/validations/profileSettingSchema.ts
- 2025.01.18
=> refactor: 회원정보 수정 폼 리팩터링

src/app/@modal/(.)detail/[id]/view/page.tsx, src/app/detail/_components/ContentsSection.tsx, src/app/detail/_components/ImageCarousel.tsx, src/app/search/_components/Pagination.tsx, src/app/search/_components/TagFilters.tsx, src/components/layout/HeaderCategorys.tsx, src/components/layout/HeaderContent.tsx, src/components/shared/CardPost.tsx, src/components/shared/LikeSection.tsx, src/components/shared/ListPost.tsx, src/components/shared/ToggleButton.tsx, src/lib/constants/constants.ts, src/lib/hooks/search/useSearchQuery.ts, src/lib/styles/globals.css
- 카테고리 - 태그 검색 기능 리팩토링
- src/app/@modal/(.)detail/[id]/view/page.tsx
- src/app/detail/_components/ContentsSection.tsx
- src/app/detail/_components/ImageCarousel.tsx
- src/app/search/_components/Pagination.tsx
- src/components/layout/HeaderCategorys.tsx
- 2025.01.25
- 검색 잘됩니다!
=> refactor: 카테고리 - 태그 검색 기능 리팩토링

src/app/bookmarks/_components/BookmarkList.tsx, src/components/layout/HeaderContent.tsx, src/lib/hooks/bookmarks/useBookmark.ts
- 북마크 편집모드 추가
- src/app/bookmarks/_components/BookmarkList.tsx
- src/lib/hooks/bookmarks/useBookmark.ts
- 2025.01.18
- 헤더 부분 제가 할 일은 완료되어 더 이상 건들 일 없을것 같습니다
=> feat: 북마크 편집모드 추가

src/app/write/_components/ImageUploadSection.tsx, src/app/write/page.tsx, src/lib/hooks/write/useFormHanlders.ts, src/lib/types/supabase.ts
- feat: thumbnail_blur_url 처리 칼럼 및 블러 처리 관련 기능 추가
- src/app/write/_components/ImageUploadSection.tsx
- src/lib/hooks/write/useFormHanlders.ts
- src/lib/types/supabase.ts
- 2025.1.18
- To. 양팀좡... 제대로 잘 했다 체킹필요.. (근데 블러처리로직은 남겨놨어용 ㅇㅅㅇ/)
=> feat: thumbnail_blur_url 처리 칼럼 및 블러 처리 관련 기능 추가

src/app/chat/new/_components/ChatRoomForm.tsx, src/app/chat/new/_components/ThumbnailUploadSection.tsx, src/app/chat/new/_components/TitleSection.tsx, src/app/chat/new/page.tsx, src/lib/validations/chatRoomSchema.ts
- refactor: 채팅방 생성 폼 수정
- src/app/chat/new/_components/ChatRoomForm.tsx
- src/app/chat/new/_components/ThumbnailUploadSection.tsx
- src/app/chat/new/_components/TitleSection.tsx
- src/app/chat/new/page.tsx
- src/lib/validations/chatRoomSchema.ts
- 2025.01.19
- 채팅방 생성 폼에서 더 이상 funnel 패턴을 사용하지 않습니다.
- 채팅방 생성 시 카테고리-태그 선택 영역이 추가되었습니다.
- 채팅방 생성 폼 UI가 변경되었습니다.
- react-hook-form과 zod로 유효성 검증이 이루어집니다.
- 필요없는 funnel 구성요소들 곧 삭제하겠슴다
- 지금보니까 파일 업로드 5MB 제한 걸어놓고 10MB까지 가능하다 해뒀네? 고쳐올게요
=> refactor: 채팅방 생성 폼 수정

src/app/bookmarks/_components/BookmarkList.tsx, src/app/home/_components/ListLender.tsx, src/app/home/_components/MasonryLayout.tsx, src/app/search/_components/SearchResults.tsx, src/components/shared/CardSkeleton.tsx, src/components/shared/GridSkeleton.tsx, src/lib/styles/globals.css, tailwind.config.ts
- 스켈레톤 ui 추가중
- 8개
- 2025.01.19
- 애니메이션 하나 더 추가햇어요
- 리스트만 하면 됩니다
=> feat: 스켈레톤 ui 추가

src/app/chat/[id]/_components/ChatMessages.tsx, src/app/chat/_components/ChatRoomCard.tsx, src/app/chat/_components/Filter.tsx, src/app/chat/page.tsx, src/lib/types/chat.ts, src/lib/utils/chat/fetchMessages.ts
- feat: 채팅방 카테고리별 필터링 추가
- src/app/chat/[id]/_components/ChatMessages.tsx
- src/app/chat/_components/ChatRoomCard.tsx
- src/app/chat/_components/Filter.tsx
- src/app/chat/page.tsx
- src/lib/types/chat.ts
- src/lib/utils/chat/fetchMessages.ts
- 2025.01.19
- 채팅방 카테고리별 필터링이 추가되었습니다.
- UI 수정중
- type any 갖다버렸습니다
=> feat: 채팅방 카테고리별 필터링 추가

package.json, src/app/detail/_components/CommentSection.tsx, src/app/detail/_components/ContentsSection.tsx, src/app/detail/_components/ContentsSkeleton.tsx, src/app/detail/_components/PurchaseList.tsx, src/app/home/_components/ListLayout.tsx, src/app/home/_components/ListLender.tsx, src/app/home/_components/MasonryLayout.tsx, src/components/shared/CardPost.tsx, src/components/shared/GridSkeleton.tsx, src/components/shared/LikeSection.tsx, src/components/shared/ListSkeleton.tsx, yarn.lock
- 스켈레톤 ui 적용
- 죄송합니다 늦었습니다
- 2025.01.19
- 스켈레톤 ui 추가했고
- 메인 리스트 masonry 레이아웃을 위한 라이브러리 바꿨습니다.
=> style: 스켈레톤 ui 적용

src/app/chat/[id]/_components/ChatGallery.tsx, src/app/chat/[id]/_components/ChatHeader.tsx, src/app/chat/[id]/_components/ChatInput.tsx, src/app/chat/_components/ChatRoomCard.tsx, src/app/chat/_components/Filter.tsx, src/app/chat/_utils/chat.ts, src/app/chat/new/_components/ThumbnailUploadSection.tsx
- fix: 채팅방 입장 처리 문제 수정
- src/app/chat/_components/ChatRoomCard.tsx
- 그외 잡다한 주석
- 2025.01.19
- 채팅방 입장 처리 로직 다시 가져왔습니다.
- 되면좋겠다
- 각종 주석 삭제했습니다.
=> fix: 채팅방 입장 처리 문제 수정

src/app/@modal/(.)detail/[id]/view/page.tsx, src/app/@modal/loading.tsx, src/app/detail/_components/ContentsSection.tsx, src/app/detail/_components/EditDelete.tsx, src/app/detail/_components/ImageCarousel.tsx, src/app/detail/_components/ImageGallery.tsx, src/app/detail/_components/PurchaseList.tsx, src/app/search/_components/SortPosts.tsx, src/lib/utils/post/deletePost.ts
- 게시물 수정버튼, 삭제버튼 추가
- src/app/@modal/(.)detail/[id]/view/page.tsx
- src/app/@modal/loading.tsx
- src/app/detail/_components/ContentsSection.tsx
- src/app/detail/_components/EditDelete.tsx
- src/app/detail/_components/ImageCarousel.tsx
- src/app/detail/_components/ImageGallery.tsx
- src/app/detail/_components/PurchaseList.tsx
- src/app/search/_components/SortPosts.tsx
- src/lib/utils/post/deletePost.ts
- 2025-01-19
- 인터셉트 모달 열릴 때 로딩 ui 추가했습니다
=> feat: 게시물 수정, 삭제기능 추가

src/components/shared/CardPost.tsx
- hover css 안되는 오류 수정
- hover css 안되는 오류 수정
- 2024.01.19
- hover css 안되는 오류 수정
=> fix: hover css 안되는 오류 수정

src/app/chat/[id]/_components/ChatMessages.tsx, src/app/search/page.tsx, src/components/layout/Header.tsx
- chore: 로딩 중 텍스트 제거
- chore: 로딩 중 텍스트 제거
- 2025.01.20
- chore: 로딩 중 텍스트 제거
=> chore: 로딩 중 텍스트 제거

src/app/home/_components/LayoutToggle.tsx
- style: 버튼 아이콘 중앙정렬
- style: 버튼 아이콘 중앙정렬
- 2025.01.20
- style: 버튼 아이콘 중앙정렬
=> style: 버튼 아이콘 중앙정렬

src/app/home/_components/MainContent.tsx
- 안내문구 조건 수정
- 긴급수정
- 2025.01.21
- 안내문구 조건 수정
=> fix: 안내문구 조건 수정

src/lib/hooks/detail/useLike.ts
- 좋아요 개수 낙관적 업데이트 적용
- 좋아요 개수 낙관적 업데이트 적용
- 2025.01.21
- 좋아요 개수 낙관적 업데이트 적용
=> fix: 좋아요 개수 낙관적 업데이트 적용

src/app/home/_components/MainContent.tsx
- 스켈레톤 ui 나오게끔 수정
- 스켈레톤 ui 나오게끔 수정
- 2025.01.21
- 죄송합니다 자꾸 나오네요
=> fix: 스켈레톤 ui 나오게끔 수정

global.d.ts, next.config.mjs, src/app/bookmarks/_components/BookmarkList.tsx, src/app/detail/_components/ContentsSection.tsx, src/app/detail/_components/EditDelete.tsx, src/app/detail/_components/SocialShare.tsx, src/app/search/_components/SortPosts.tsx, src/components/common/KakaoScript.tsx, src/components/layout/SearchBar.tsx, src/components/ui/Dropdown.tsx, src/lib/styles/globals.css, tsconfig.json
- 소셜 공유 기능 추가
- global.d.ts
- next.config.mjs
- 2025.01.22
- 프로젝트 초반에 허용했던 unsplash 도메인 삭제했습니다.
- 늦었지만 shadow 관련 css 를 정의했습니다
- 드롭다운 UI가 3개가 됨으로써 그냥 공통 컴포넌트로 분리했습니다
- global.d.ts 와 tsconfig 수정사항은 카카오톡 공유를 next.js 14 프로젝트에 적용시키는 과정에서 추가한 카카오톡 타입입니다
=> feat: 소셜 공유 기능 추가

src/app/detail/_components/DeleteConfirm.tsx, src/app/detail/_components/EditDelete.tsx, src/app/detail/_components/ImageGallery.tsx, src/lib/hooks/common/useModal.ts
-  모달 관련 커스텀훅 추가
- src/app/detail/_components/DeleteConfirm.tsx
- src/app/detail/_components/EditDelete.tsx
- src/app/detail/_components/ImageGallery.tsx
- src/lib/hooks/common/useModal.ts
- YYYY.MM.DD
- 훨씬 깔끔해진것 같습니다
=> refactor:  모달 관련 커스텀훅 추가

src/app/bookmark/_components/BookmarkList.tsx, src/app/bookmark/_components/LikedPostList.tsx, src/app/layout.tsx, src/app/search/_components/Pagination.tsx, src/app/search/_components/SearchResults.tsx, src/app/search/page.tsx, src/components/shared/GridPost.tsx, src/components/ui/Tags.tsx, tailwind.config.ts
- tailwind.config.ts 를 수정하였기 때문에 중간 커밋 한번 하겠습니다
- 북마크 페이지 모바일 화면 완성되었습니다
- 2025.01.22
- search 페이지 진행중입니다
=> style: 북마크 페이지 반응형 완료

src/app/write/[id]/page.tsx, src/app/write/_components/AddressModal.tsx, src/lib/utils/mypage/userInfo.ts, src/lib/utils/post/fetchPost.ts, src/lib/utils/search/fetchSearchPosts.tsx
- fix: is_saved true 변경으로 인한 이미지 업로드 되지 않는 이슈 처리
- src/lib/utils/mypage/userInfo.ts
- src/lib/utils/post/fetchPost.ts
- src/lib/utils/search/fetchSearchPosts.tsx
- 2025.1.22
- 임시저장기능 개발 중, 이미지 렌더링 과정 도중 발생한 오류 처리 수정했습니다 ^-^)v
=> fix: is_saved true 변경으로 인한 이미지 업로드 되지 않는 이슈 처리

src/lib/hooks/write/usePostQueries.ts
- fix: .eq("is_saved", false) 추가 [에러 수정]
- src/lib/hooks/write/usePostQueries.ts
- 2025.1.22
- 이미지 안뜨는 이슈 해결 완
=> fix: .eq("is_saved", false) 추가 [에러 수정]

src/app/search/_components/TagCheckFilters.tsx, src/app/search/page.tsx, src/components/layout/HeaderContent.tsx
- 헤더 아래에 이상한게 보이는 버그 수정
- 헤더 아래에 이상한게 보이는 버그 수정
- 2025.01.22
- 헤더 아래에 이상한게 보이는 버그 수정
=> fix: 헤더 아래에 이상한게 보이는 버그 수정

src/app/mypage/_components/AccountSettingTabs.tsx, src/app/mypage/_components/AgreementContent.tsx, src/app/mypage/_components/CardsSkeleton.tsx, src/app/mypage/_components/MyPosts.tsx, src/app/mypage/_components/ProfileSkeleton.tsx, src/app/mypage/_components/RecentViewPosts.tsx, src/app/mypage/_components/ServiceContent.tsx, src/app/mypage/_components/StatsCard.tsx, src/app/mypage/_components/VerificationSection.tsx, src/app/mypage/profile-setting/_components/ProfileSettingsForm.tsx, src/components/ui/Modal.tsx, src/lib/hooks/mypage/useDevicePreference.ts, src/lib/utils/supabase/middleware.ts, src/middleware.ts
- chore: UT 기간 중 미들웨어 잠시 해제
반응형 작업하다가 UT 기간 동안 미들웨어 해제했습니다
- mypage/_components/ 컴포넌트들
- middleware.ts
- lib/utils/supabase/middleware.ts
- 2025.01.23
- UT 기간 끝나면 다시 미들웨어 적용 필요
=> chore: UT 기간 중 미들웨어 잠시 해제

src/app/layout.tsx, src/components/shared/LikeSection.tsx
- 메타데이터 이미지 조정
- 메타데이터 이미지 조정
- 2025.01.23
- 메타데이터 이미지 조정
=> chore: 메타데이터 이미지 조정

src/app/mypage/_components/MyPosts.tsx, src/app/mypage/_components/StatCard.tsx, src/app/mypage/_components/StatCardsSkeleton.tsx, src/app/mypage/_components/VerificationSection.tsx, src/app/mypage/loading.tsx, src/app/mypage/profile-setting/_components/CameraButton.tsx, src/app/mypage/profile-setting/_components/GenderSelection.tsx, src/app/mypage/profile-setting/_components/ProfileEditTextField.tsx, src/app/mypage/profile-setting/_components/ProfileImageUploadSection.tsx, src/app/mypage/profile-setting/_components/ProfileSettingsForm.tsx, src/app/mypage/profile-setting/loading.tsx, src/app/mypage/profile-setting/page.tsx, src/components/shared/LoadingSpinner.tsx
- style: 회원정보 페이지 반응형 및 스켈로톤 적용
- 마이페이지 컴포넌트 반응형 적용시켰습니다. 
- loading.tsx 만들어 스켈로톤 적용하였습니다.
- 정보를 불러와 isPending일때도 스켈로톤이 뜨도록 적용시켰습니다.
- 2025.01.24
=> style: 회원정보 페이지 반응형 및 스켈로톤 적용

src/app/detail/_components/CommentMoblie.tsx, src/app/detail/_components/ContentsSection.tsx, src/app/detail/_components/EditDelete.tsx, src/app/detail/_components/ImageCarousel.tsx, src/components/ui/Dropdown.tsx, src/components/ui/SlideOver.tsx, src/lib/styles/globals.css
- 상세페이지 반응형 완료
- 모바일버전에서의 slideover 레이아웃들과 댓글 기능을 마무리하였습니다.
- 2025.01.24
- 상세페이지 이것 저것 확인해보시고, 사용할 UI 가있으시다면 말씀해주길 바라겠습니다.
=> style: 상세페이지 반응형 완료

src/app/write/[id]/page.tsx, src/app/write/_components/TempSaveModal.tsx, src/app/write/page.tsx, src/components/shared/ScrollTopButton.tsx, src/lib/hooks/write/useFormHandlers.ts, src/lib/hooks/write/useFormStateHandlers.ts, src/lib/hooks/write/usePostHandlers.ts, src/lib/hooks/write/usePurchaseHandlers.ts, src/lib/hooks/write/useTagHandlers.ts, src/lib/hooks/write/useTempSaveHandlers.ts
- feat & fix: 위로 올라가는 플로팅 버튼 등의 자잘한 편의기능 추가 및 핸들러 작동오류 수정
- src/app/write/[id]/page.tsx
- src/app/write/_components/TempSaveModal.tsx
- src/components/shared/ScrollTopButton.tsx
- src/lib/hooks/write/useFormHandlers.ts
- src/lib/hooks/write/useFormStateHandlers.ts
- src/lib/hooks/write/usePostHandlers.ts
- src/lib/hooks/write/usePurchaseHandlers.ts
- src/lib/hooks/write/useTagHandlers.ts
- src/lib/hooks/write/useTempSaveHandlers.ts
- 2025.1.24
- 상태연동을 안해줘서.. 기능이 작동을 안하는 이슈를 수정했습니다. (까먹은 림졍 반성해!)
- UT 피드백 중 내려갈 때, 위로 올릴 수 있는 버튼이 있었으면 좋겠다는 의견을 방안해서 임의로 우선 올라가는 버튼을 만들었습니다.
(작동은 스크롤하면서 올라가게끔 되어있습니다. 크기와 이외의 사항은 아직 반영하지않았으니 추후에 수정하는 방안으로 가면 좋을 듯. 합니다.)
- 게시글 업로드 후, 임시저장 게시글이 사라지지 않는 이슈를 해결했습니다. (바보같이 임시저장 기능에 집중하다가 발생한 오류였네요 끄흡)
=> feat & fix: 위로 올라가는 플로팅 버튼 등의 자잘한 편의기능 추가 및 핸들러 작동오류 수정

src/app/layout.tsx, src/components/layout/NavItem.tsx, src/components/layout/SearchBar.tsx, src/components/ui/Dropdown.tsx
- 테스트하다가 지운 조건 다시 업데이트
- 테스트하다가 지운 조건 다시 업데이트
- 2025.01.24
- 테스트하다가 지운 조건 다시 업데이트
=> fix: 테스트하다가 지운 조건 다시 업데이트

src/app/chat/new/_components/ChatRoomForm.tsx, src/app/chat/new/_components/ThumbnailUploadSection.tsx, src/app/chat/new/_components/TitleSection.tsx, src/app/chat/new/page.tsx, src/components/shared/TagSection.tsx, src/lib/validations/chatRoomSchema.ts
- style: 채팅방 생성 페이지 모바일 시안 반영
- src/app/chat/new/_components/ChatRoomForm.tsx
- src/app/chat/new/_components/ThumbnailUploadSection.tsx
- src/app/chat/new/_components/TitleSection.tsx
- src/app/chat/new/page.tsx
- src/components/shared/TagSection.tsx
- YYYY.MM.DD
- 유효성 검증이 좀 고장났습니다 고쳐오겠습니다
- PR 끊어서 올리겠슴다
=> style: 채팅방 생성 페이지 모바일 시안 반영

src/app/write/[id]/page.tsx, src/app/write/_components/ContentSection.tsx, src/app/write/_components/ImageUploadSection.tsx, src/app/write/_components/LocationSection.tsx, src/app/write/_components/ProductSection.tsx, src/app/write/_components/PurchaseModal.tsx, src/app/write/_components/TempSaveModal.tsx, src/app/write/page.tsx, src/components/shared/TagSection.tsx, src/lib/hooks/write/useFormHandlers.ts, src/lib/hooks/write/usePostHandlers.ts, src/lib/hooks/write/usePostQueries.ts
- feat & fix: UT 피드백에 따른 페이지 디자인 수정 및 기능 추가(필수값 유효성 검사), 그리고 thumbnail_blur_url, base64 형식으로 수정
- src/app/write/[id]/page.tsx
- src/app/write/_components/ContentSection.tsx
- src/app/write/_components/ImageUploadSection.tsx
- src/app/write/_components/LocationSection.tsx
- src/app/write/_components/ProductSection.tsx
- src/app/write/_components/PurchaseModal.tsx
- src/app/write/_components/TempSaveModal.tsx
- src/components/shared/TagSection.tsx
- src/lib/hooks/write/useFormHandlers.ts
- src/lib/hooks/write/usePostHandlers.ts
- src/lib/hooks/write/usePostQueries.ts
- 2025.1.27
- UX 개선, UT 피드백을 바탕으로 세미 유효성검사 기능 추가했습니다.
- 수정페이지에서 돌아가기 버튼을 누르면, supabase 스토리지에 이미지가 남는 이슈 현상을 해결했습니다.
- thumbnail_blur_url, base64 형식으로 변환했습니다. 2상.
=> feat & fix: UT 피드백에 따른 페이지 디자인 수정 및 기능 추가(필수값 유효성 검사), 그리고 thumbnail_blur_url, base64 형식으로 수정

src/app/write/[id]/page.tsx, src/app/write/page.tsx
- fix: 스토리지에 이미지 안올라가는 이슈 수정중 (우선 원상복구)
- src/app/write/[id]/page.tsx
- 2025.1.28
- 스토리지 오남용을 피하기 위해.. 기능을 추가했으나..
페이지 이동하거나 **새로고침**할 때... (~~이게 너무 치명적..~~) 이미지를 지우게끔 로직이 되어있어서 이렇더라고요..
- 이미지는 걍 로컬스토리지... 아닌 이상 절대 건드리지 않겠습니다. ~~오남용 압수임 ㄹㅇ~~
=> fix: 스토리지에 이미지 안올라가는 이슈 수정중 (우선 원상복구)

src/app/mypage/_components/AccountDeleteContent.tsx, src/app/mypage/_components/AccountSettingTabs.tsx, src/lib/validations/profileSchema.ts
- fix: 회원정보 수정 페이지 닉네임 길이 수정
- profileSchema.ts
- 2025.01.31
=> fix: 회원정보 수정 페이지 닉네임 길이 수정

src/app/home/_components/MainContent.tsx, src/app/write/_components/PostTagSection.tsx, src/components/shared/ScrollTopButton.tsx, src/components/ui/FloatingButton.tsx, src/lib/constants/constants.ts, src/lib/hooks/write/useTagHandlers.ts
- style: 플로팅 버튼 시안에 맞게 수정
- src/app/home/_components/MainContent.tsx
- src/components/shared/ScrollTopButton.tsx
- src/components/ui/FloatingButton.tsx
- 2025.2.3
- 홈 화면에 플로팅 버튼 상단에 Top버튼 추가했습니다.
- 디자인 QA 크기 변경과 그림자 추가 완료.
=> style: 플로팅 버튼 시안에 맞게 수정

src/app/write/[id]/_components/ExitOrContinueModal.tsx, src/app/write/[id]/page.tsx, src/app/write/_components/AddressModal.tsx, src/app/write/_components/BodySizeSection.tsx, src/app/write/_components/ContentSection.tsx, src/app/write/_components/ImageUploadMobile.tsx, src/app/write/_components/ImageUploadSection.tsx, src/app/write/_components/LocationSection.tsx, src/app/write/_components/PostForm.tsx, src/app/write/_components/PostTagSection.tsx, src/app/write/_components/SubmitButton.tsx, src/app/write/_components/TagModal.tsx, src/lib/hooks/write/useEditPageState.ts, src/lib/hooks/write/useTagHandlers.ts, src/lib/utils/write/tag.ts
- feat: 태그섹션 반응형 디자인 완료 및 수정페이지 모달 추가
- 1..5개
- 2025.2.4
- 수정페이지에서도 데이터 변경 시, 모달 뜨도록 기능추가했습니다.
- 스타일 통일을 위해 모든 컴포넌트, BreakPoints 적용 완료했습니다.
- 태그 반응형 적용 완료, 남은건 상품 모달 뿐...
=> feat: 태그섹션 반응형 디자인 완료 및 수정페이지 모달 추가

src/app/(auth)/login/page.tsx, src/app/detail/[id]/page.tsx, src/app/detail/_components/SocialShare.tsx, src/app/layout.tsx, src/app/mypage/page.tsx, src/app/profile/[id]/page.tsx
- chore: 메타데이터 FitFor로 수정
- metadata를 사용하는 모든 파일
- 2025.02.04
=> chore: 메타데이터 FitFor로 수정

src/app/bookmark/_components/PostList.tsx, src/app/detail/_components/ContentsSection.tsx, src/components/ui/Button.tsx
- 마지막 디자인 QA 수정
- 북마크페이지 버튼, 콘텐츠 조회수 날짜 부분 간격
- 2025.02.05
-
=> style: 마지막 디자인 QA 수정

src/app/chat/[id]/_components/ChatGallery.tsx, src/app/chat/[id]/_components/ChatInput.tsx, src/app/chat/[id]/_components/ChatRoom.tsx, src/app/chat/_components/ChatRoomList.tsx, src/app/chat/_components/RoomFilterMobile.tsx, src/app/chat/_components/SortChatRooms.tsx, src/app/chat/_components/TagFilters.tsx, src/app/chat/_components/fetchChatRooms.ts, src/app/chat/new/_components/ChatRoomForm.tsx, src/app/chat/page.tsx, src/lib/hooks/chat/useChatInput.ts, src/lib/hooks/chat/useChatRooms.ts, src/lib/utils/chat/chat.ts, src/lib/utils/chat/createRoomHandler.ts, src/lib/utils/chat/uploadThumbnail.ts
- fix: 채팅방 멤버 입장 로직 누락 수정
- src/app/chat/[id]/_components/ChatGallery.tsx
- src/app/chat/[id]/_components/ChatInput.tsx
- src/app/chat/[id]/_components/ChatRoom.tsx
- src/app/chat/_components/ChatRoomList.tsx
- src/app/chat/_components/RoomFilterMobile.tsx
- src/app/chat/_components/TagFilters.tsx
- src/app/chat/page.tsx
- src/lib/hooks/chat/useChatInput.ts
- src/lib/hooks/chat/useChatRooms.ts
- src/lib/utils/chat/chat.ts
- 2025.02.05
- 일반 멤버로 채팅방에 입장 시 채팅 입력이 불가능한 오류가 수정되었습니다.
- 채팅 기능이 인증 유저 전용으로 작동하도록 수정되었습니다. (채팅방 관리자 제외)
=> fix: 채팅방 멤버 입장 로직 누락 수정

src/app/home/_components/MainContent.tsx, src/app/write/_components/AddressModal.tsx, src/app/write/_components/ProductListModal.tsx, src/components/shared/ScrollTopButton.tsx, src/lib/hooks/write/usePostHandlers.ts
- fix: 모달 내부 스크롤 제거 및 모바일 등록버튼 이슈 수정, 그리고 디자인 QA에 따른 ScrollTopButton.tsx 동작 수정
- src/app/home/_components/MainContent.tsx
- src/app/write/_components/AddressModal.tsx
- src/app/write/_components/ProductListModal.tsx
- src/components/shared/ScrollTopButton.tsx
- src/lib/hooks/write/usePostHandlers.ts
- 2025.2.5
- `ModalItem`을 사용하지 않은 모달의 경우, 모달에서 외부 스크롤이 나오는 이슈가 존재 -> `useLockScroll`활용하여 해결했습니다.
- tb 환경에서 ~또다시..~ disabled로 나와야하는 Submit 버튼에 해당 사항이 적용되지 않는 이슈가 발생하여 수정했습니다.
- 디자인 QA에 맞게 스크롤 버튼 활성을 수정했습니다.
- TMI : 허리핑 옮은듯.
=> fix: 모달 내부 스크롤 제거 및 모바일 등록버튼 이슈 수정, 그리고 디자인 QA에 따른 ScrollTopButton.tsx 동작 수정

src/app/chat/[id]/_components/ChatHeader.tsx, src/components/ui/Dropdown.tsx
- feat: 채팅방 삭제 버튼
- src/app/chat/[id]/_components/ChatHeader.tsx
- src/components/ui/Dropdown.tsx
- 2025.02.06
- 채팅방 삭제 버튼 다시 살렸습니다(방장 전용)
=> feat: 채팅방 삭제 버튼

src/app/write/[id]/page.tsx, src/lib/hooks/write/usePostHandlers.ts
- fix: 수정하기 버튼을 누르면 모달이 나오는 현상 긴급 수정
- src/app/write/[id]/page.tsx
- src/lib/hooks/write/usePostHandlers.ts
- 2025.2.7
- 시안영상을 찍던 중, 수정하기 버튼을 누를 때.. 이탈 시 나오는 모달이 나오게 되어 긴급수정하였습니다.
- 여기서 끝났으면 좋았겠지만... 해당 사항은 어떻게 보면 치명적인 부분이라.. 수정해서 올리게 되었습니다. 제 불찰입니다..
(바보 림졍을 탓해줘..)
=> fix: 수정하기 버튼을 누르면 모달이 나오는 현상 긴급 수정

next.config.mjs, src/app/page.tsx
- 홈 리다이렉트 에러페이지 출력 수정
- 홈 리다이렉트 에러페이지 출력 수정
- 2025.02.07
- 홈 리다이렉트 에러페이지 출력 수정
=> fix: 홈 리다이렉트 에러페이지 출력 수정

src/app/chat/[id]/_components/ChatInput.tsx
- fix: 인증유저 아닐 시 textarea 수정
- fix: 인증유저 아닐 시 textarea 수정
- 2025.02.07
- fix: 인증유저 아닐 시 textarea 수정
=> fix: 인증유저 아닐 시 textarea 수정

src/lib/utils/chat/chat.ts
- fix: 채팅방 파일 업로드 alert
-
- 2025.02.07
-
=> fix: 채팅방 파일 업로드 alert
